shift/urls.py
from django.urls import path
from . import views

app_name = 'shift'

urlpatterns = [
    path('', views.index, name='index'),
]

sns/urls.py
from django.urls import path 
from . import views

app_name = 'sns'

urlpatterns = [
    path('', views.index, name='index'),
    path('groups', views.groups, name='groups'),
    path('add', views.add, name='add'),
    path('creategroup', views.creategroup, name='creategroup'),
    path('post', views.post, name='post'),
    path('share/<int:share_id>', views.share, name='share'),
    path('good/<int:good_id>', views.good, name='good'),
]

tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings
from tutorial.views.main import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('kakeibo/', include('kakeibo.urls')),
    path('sns/', include('sns.urls')),
    path('shift/', include('shift.urls')),
    path('cms/', include('cms.urls.ajax')),
    path('api/cms/', include('cms.urls.api')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shift/models.py
from django.db import models
import datetime
from django.db.models.fields import DateField

# Create your models here.


class employee(models.Model):

    class Meta:
        # テーブル名
        db_table = "employee"
        verbose_name = "アルバイト"  # 追加
        verbose_name_plural = "アルバイト"

    # カラムの定義
    id = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name="名前", max_length=20, unique=True)

    def __str__(self):
        return self.name


class schedule(models.Model):

    class Meta:
        # テーブル名
        db_table = "schedule"
        verbose_name = "シフト予定表"  # 追加

    # カラムの定義
    id = models.AutoField(primary_key=True)
    emp = models.ForeignKey(employee, on_delete=models.PROTECT)
    date = models.DateField(null=True)
    start_at = models.TimeField(null=True)
    end_at = models.TimeField(null=True)

    @classmethod
    def getTodayShift(cls, day):
        TodayShift = cls.objects.filter(
            date=day,
        )
        return TodayShift

    @classmethod
    def getHisShift(cls, name):

        hisShift = cls.objects.filter(
            emp=employee(name=name),
        )
        return hisShift

    def __str__(self):
        return self.id

shift/forms.py
from django import forms


LIBRARIES_CHOICES = (
    ('submit', 'submit'),
    ('cancel', 'cancel'),
    ('check', 'check'),
    ('calculate', 'calculate'),
)


class shiftForm(forms.Form):
    type = forms.ChoiceField(
        label='操作',
        widget=forms.Select,
        choices=LIBRARIES_CHOICES,
        required=True,
    )
    name = forms.CharField(label="名前", max_length=20, required=True)
    date = forms.DateField(label='日付', required=False)
    start_at = forms.TimeField(label='開始時間', required=False, initial=None)
    end_at = forms.TimeField(label='終了時間', required=False, initial=None)

shift/views.py
from django.shortcuts import render, redirect
from .models import employee, schedule
from .forms import shiftForm
from .services import preProcess, StoreShift
import re

# Create your views here.


def index(request):
    result = []
    if request.method == 'POST':
        print(request.POST)
        lines = []
        lines.append(request.POST['type'])
        lines.append(request.POST['name'])
        if any(request.POST['type'] == t for t in ('submit', 'cancel')):
            if all(request.POST[col] != '' for col in ('date', 'start_at', 'end_at')):
                dt = str(request.POST['date']) + ' ' + \
                    str(request.POST['start_at']) + \
                    '-' + str(request.POST['end_at'])
                lines.append(dt)
            else:
                result.append('worng form')
                return render(request, 'shift/index.html', {'form': shiftForm, 'result': result})
        print('lines')
        print(lines)
        TERM, K, queries = preProcess(lines)
        store = StoreShift(K, TERM)
        for q in queries:
            result.append(store.query_process(q))
    else:
        result = None
    return render(request, 'shift/index.html', {'form': shiftForm, 'result': result})

shift/templates/shift/index.html
{% extends 'shift/layout.html' %}

{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        {{result}}
        <form action="{% url 'shift:index' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" label="送信">
        </form>
    </div>
</div>
{% endblock content %}

shift/templates/shift/layout.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>シフト管理</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<body>
    <div class="body_content">
        <div class="body_content_inner">
            {% block content %}
            <!-- block content ～ endblockの間に子テンプレートの内容が差し込まれる -->
            {% endblock %}
        </div>
    </div>
</body>
<script>
      $(function () {
          // datepicker
          let dateFormat = 'yy/mm/dd';
          $('#id_date').datepicker({
              dateFormat: dateFormat
          });

          // timedropper
          $("#id_start_at").timeDropper({
              format: "H:mm",
              setCurrentTime: false,
          });

          
          // timedropper
          $("#id_end_at").timeDropper({
              format: "H:mm",
              setCurrentTime: false,
          });

      });
  </script>
</html>