sns/urls.py
from django.urls import path 
from . import views

app_name = 'sns'

urlpatterns = [
    path('', views.index, name='index'),
    path('groups', views.groups, name='groups'),
    path('add', views.add, name='add'),
    path('creategroup', views.creategroup, name='creategroup'),
    path('post', views.post, name='post'),
    path('share/<int:share_id>', views.share, name='share'),
    path('good/<int:good_id>', views.good, name='good'),
]

tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings
from tutorial.views.main import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('kakeibo/', include('kakeibo.urls')),
    path('sns/', include('sns.urls')),
    path('shift/', include('shift.urls')),
    path('cms/', include('cms.urls.ajax')),
    path('api/cms/', include('cms.urls.api')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sns/models.py
from django.db import models
from django.contrib.auth.models import User

# Messageクラス
class Message(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, \
            related_name='message_owner')
    group = models.ForeignKey('Group', on_delete=models.CASCADE)
    content = models.TextField(max_length=1000)
    share_id = models.IntegerField(default=-1)
    good_count = models.IntegerField(default=0)
    share_count = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content) + ' (' + str(self.owner) + ')'

    def get_share(self):
        return Message.objects.get(id=self.share_id)

    class Meta:
        ordering = ('-pub_date',)

# Groupクラス（最初に管理者をownerとしてmainグループを作ります。mainへの投稿はすべての人が閲覧できます。）
class Group(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, \
            related_name='group_owner')
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

# Friendクラス
class Friend(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, \
            related_name='friend_owner')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user) + ' (group:"' + str(self.group) + '")'

# Goodクラス
class Good(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, \
            related_name='good_owner')
    message = models.ForeignKey(Message, on_delete=models.CASCADE)

    def __str__(self):
        return 'good for "' + str(self.message) + '" (by ' + \
                str(self.owner) + ')'

sns/forms.py
from django import forms
from.models import Message,Group,Friend,Good
from django.contrib.auth.models import User

# Messageのフォーム（未使用）
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['owner','group','content']

# Groupのフォーム（未使用）
class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['owner', 'title']

# Friendのフォーム（未使用）
class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ['owner', 'user', 'group']

# Goodのフォーム（未使用）
class GoodForm(forms.ModelForm):
    class Meta:
        model = Good
        fields = ['owner', 'message']

# 検索フォーム
class SearchForm(forms.Form):
    search = forms.CharField(max_length=100)

# Groupのチェックボックスフォーム
class GroupCheckForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(GroupCheckForm, self).__init__(*args, **kwargs)
        public = User.objects.filter(username='public').first()
        self.fields['groups'] = forms.MultipleChoiceField(
            choices=[(item.title, item.title) for item in \
                 Group.objects.filter(owner__in=[user,public])],
            widget=forms.CheckboxSelectMultiple(),
        )

# Groupの選択メニューフォーム
class GroupSelectForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(GroupSelectForm, self).__init__(*args, **kwargs)
        self.fields['groups'] = forms.ChoiceField(
            choices=[('-','-')] + [(item.title, item.title) \
                 for item in Group.objects.filter(owner=user)],
        )

# Friendのチェックボックスフォーム
class FriendsForm(forms.Form):
    def __init__(self, user, friends=[], vals=[], *args, **kwargs):
        super(FriendsForm, self).__init__(*args, **kwargs)
        self.fields['friends'] = forms.MultipleChoiceField(
            choices=[(item.user, item.user) for item in friends],
            widget=forms.CheckboxSelectMultiple(),
            initial=vals
        )

# Group作成フォーム
class CreateGroupForm(forms.Form):
    group_name = forms.CharField(max_length=50)

# 投稿フォーム
class PostForm(forms.Form):
    content = forms.CharField(max_length=500, \
            widget=forms.Textarea)

    def __init__(self, user, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        public = User.objects.filter(username='public').first()
        self.fields['groups'] = forms.ChoiceField(
            choices=[('-','-')] + [(item.title, item.title) \
                     for item in Group.objects. \
                     filter(owner__in=[user,public])],
        )

sns/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .forms import GroupCheckForm, GroupSelectForm,\
    SearchForm, FriendsForm, CreateGroupForm, PostForm
from .models import Message, Friend, Group, Good
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.shortcuts import render

# Create your views here.


# indexのビュー関数


@login_required(login_url='/admin/login/')
def index(request):
    # publicのuserを取得
    (public_user, public_group) = get_public()

    # POST送信時の処理
    if request.method == 'POST':

        # Groupsのチェックを更新した時の処理
        if request.POST['mode'] == '__check_form__':
            # フォームの用意
            searchform = SearchForm()
            checkform = GroupCheckForm(request.user, request.POST)
            # チェックされたGroup名をリストにまとめる
            glist = []
            for item in request.POST.getlist('groups'):
                glist.append(item)
            # Messageの取得
            messages = get_your_group_message(request.user,
                                              glist, None)

        # Groupsメニューを変更した時の処理
        if request.POST['mode'] == '__search_form__':
            # フォームの用意
            searchform = SearchForm(request.POST)
            checkform = GroupCheckForm(request.user)
            # Groupのリストを取得
            gps = Group.objects.filter(owner=request.user)
            glist = [public_group]
            for item in gps:
                glist.append(item)
            # メッセージを取得
            messages = get_your_group_message(request.user, glist,
                                              request.POST['search'])

    # GETアクセス時の処理
    else:
        # フォームの用意
        searchform = SearchForm()
        checkform = GroupCheckForm(request.user)
        # Groupのリストを取得
        gps = Group.objects.filter(owner=request.user)
        glist = [public_group]
        for item in gps:
            glist.append(item)
        # メッセージの取得
        messages = get_your_group_message(request.user, glist, None)

    #　共通処理
    params = {
        'login_user': request.user,
        'contents': messages,
        'check_form': checkform,
        'search_form': searchform,
    }
    return render(request, 'sns/index.html', params)


@login_required(login_url='/admin/login/')
def groups(request):
    # 自分が登録したFriendを取得
    friends = Friend.objects.filter(owner=request.user)

    # POST送信時の処理
    if request.method == 'POST':

        # Groupsメニュー選択肢の処理
        if request.POST['mode'] == '__groups_form__':
            # 選択したGroup名を取得
            sel_group = request.POST['groups']
            # Grooupを取得
            gp = Group.objects.filter(owner=request.user) \
                .filter(title=sel_group).first()
            # Groupに含まれるFriendを取得
            fds = Friend.objects.filter(owner=request.user) \
                .filter(group=gp)
            # FriendのUserをリストにまとめる
            vlist = []
            for item in fds:
                vlist.append(item.user.username)
            # フォームの用意
            groupsform = GroupSelectForm(request.user, request.POST)
            friendsform = FriendsForm(request.user,
                                      friends=friends, vals=vlist)

        # Friendsのチェック更新時の処理
        if request.POST['mode'] == '__friends_form__':
            # 選択したGroupの取得
            sel_group = request.POST['group']
            group_obj = Group.objects.filter(title=sel_group).first()
            if not group_obj:
                messages.info(request, "先にグループを選択してください")
                return redirect(to='/sns/groups')
            # チェックしたFriendsを取得
            sel_fds = request.POST.getlist('friends')
            # FriendsのUserを取得
            sel_users = User.objects.filter(username__in=sel_fds)
            # Userのリストに含まれるユーザーが登録したFriendを取得
            fds = Friend.objects.filter(owner=request.user) \
                .filter(user__in=sel_users)
            # すべてのFriendにGroupを設定し保存する
            vlist = []
            for item in fds:
                item.group = group_obj
                item.save()
                vlist.append(item.user.username)
            # メッセージを設定
            messages.success(request, ' チェックされたFriendを' +
                             sel_group + 'に登録しました。')
            # フォームの用意
            groupsform = GroupSelectForm(request.user,
                                         {'groups': sel_group})
            friendsform = FriendsForm(request.user,
                                      friends=friends, vals=vlist)

    # GETアクセス時の処理
    else:
        # フォームの用意
        groupsform = GroupSelectForm(request.user)
        friendsform = FriendsForm(request.user, friends=friends,
                                  vals=[])
        sel_group = '-'

    # 共通処理
    createform = CreateGroupForm()
    params = {
        'login_user': request.user,
        'groups_form': groupsform,
        'friends_form': friendsform,
        'create_form': createform,
        'group': sel_group,
    }
    return render(request, 'sns/groups.html', params)

# Friendの追加処理


@login_required(login_url='/admin/login/')
def add(request):
    # 追加するUserを取得
    add_name = request.GET['name']
    add_user = User.objects.filter(username=add_name).first()
    # Userが本人だった場合の処理
    if add_user == request.user:
        messages.info(request, "自分自身をFriendに追加することはできません。")
        return redirect(to='/sns')
    # publicの取得
    (public_user, public_group) = get_public()
    # add_userのFriendの数を調べる
    frd_num = Friend.objects.filter(owner=request.user) \
        .filter(user=add_user).count()
    # ゼロより大きければ既に登録済み
    if frd_num > 0:
        messages.info(request, add_user.username +
                      ' は既に追加されています。')
        return redirect(to='/sns')

    # ここからFriendの登録処理
    frd = Friend()
    frd.owner = request.user
    frd.user = add_user
    frd.group = public_group
    frd.save()
    # メッセージを設定
    messages.success(request, add_user.username + ' を追加しました！　\
            groupページに移動して、追加したFriendをメンバーに設定して下さい。')
    return redirect(to='/sns')

# グループの作成処理


@login_required(login_url='/admin/login/')
def creategroup(request):
    # Groupを作り、Userとtitleを設定して保存する
    gp = Group()
    gp.owner = request.user
    gp.title = request.POST['group_name']
    gp.save()
    messages.info(request, '新しいグループを作成しました。')
    return redirect(to='/sns/groups')

# メッセージのポスト処理


@login_required(login_url='/admin/login/')
def post(request):
    # POST送信の処理
    if request.method == 'POST':
        # 送信内容の取得
        gr_name = request.POST['groups']
        content = request.POST['content']
        # Groupの取得
        group = Group.objects.filter(owner=request.user) \
            .filter(title=gr_name).first()
        if group == None:
            (pub_user, group) = get_public()
        # Messageを作成し設定して保存
        msg = Message()
        msg.owner = request.user
        msg.group = group
        msg.content = content
        msg.save()
        # メッセージを設定
        messages.success(request, '新しいメッセージを投稿しました！')
        return redirect(to='/sns')

    # GETアクセス時の処理
    else:
        form = PostForm(request.user)

    # 共通処理
    params = {
        'login_user': request.user,
        'form': form,
    }
    return render(request, 'sns/post.html', params)

# 投稿をシェアする


@login_required(login_url='/admin/login/')
def share(request, share_id):
    # シェアするMessageの取得
    share = Message.objects.get(id=share_id)

    # POST送信時の処理
    if request.method == 'POST':
        # 送信内容を取得
        gr_name = request.POST['groups']
        content = request.POST['content']
        # Groupの取得
        group = Group.objects.filter(owner=request.user) \
            .filter(title=gr_name).first()
        if group == None:
            (pub_user, group) = get_public()
        # メッセージを作成し、設定をして保存
        msg = Message()
        msg.owner = request.user
        msg.group = group
        msg.content = content
        msg.share_id = share.id
        msg.save()
        share_msg = msg.get_share()
        share_msg.share_count += 1
        share_msg.save()
        # メッセージを設定
        messages.success(request, 'メッセージをシェアしました！')
        return redirect(to='/sns')

    # 共通処理
    form = PostForm(request.user)
    params = {
        'login_user': request.user,
        'form': form,
        'share': share,
    }
    return render(request, 'sns/share.html', params)

# goodボタンの処理


@login_required(login_url='/admin/login/')
def good(request, good_id):
    # goodするMessageを取得
    good_msg = Message.objects.get(id=good_id)
    # 自分がメッセージにGoodした数を調べる
    is_good = Good.objects.filter(owner=request.user) \
        .filter(message=good_msg).count()
    # ゼロより大きければ既にgood済み
    if is_good > 0:
        messages.success(request, '既にメッセージにはGoodしています。')
        return redirect(to='/sns')

    # Messageのgood_countを１増やす
    good_msg.good_count += 1
    good_msg.save()
    # Goodを作成し、設定して保存
    good = Good()
    good.owner = request.user
    good.message = good_msg
    good.save()
    # メッセージを設定
    messages.success(request, 'メッセージにGoodしました！')
    return redirect(to='/sns')

# これ以降はビュー関数ではなく普通の関数==================

# 指定されたグループおよび検索文字によるMessageの取得


def get_your_group_message(owner, glist, find):
    # publicの取得
    (public_user, public_group) = get_public()
    # チェックされたGroupの取得
    groups = Group.objects.filter(Q(owner=owner)
                                  | Q(owner=public_user)).filter(title__in=glist)
    # Groupに含まれるFriendの取得
    me_friends = Friend.objects.filter(group__in=groups)
    # FriendのUserをリストにまとめる
    me_users = []
    for f in me_friends:
        me_users.append(f.user)
    # UserリストのUserが作ったGroupの取得
    his_groups = Group.objects.filter(owner__in=me_users)
    his_friends = Friend.objects.filter(user=owner) \
        .filter(group__in=his_groups)
    me_groups = []
    for hf in his_friends:
        me_groups.append(hf.group)
    # groupがgroupsに含まれるか、me_groupsに含まれるMessageの取得
    if find == None:
        messages = Message.objects.filter(Q(group__in=groups)

sns/templates/sns/groups.html
{% extends 'sns/layout.html' %}

{% block title %}Grooups{% endblock %}

{% block header %}
<h1>Group</h1>
<p class="caption">※グループを選択してselect memberすると、そのグループに登録されている利用者がONになります。
利用者のチェックをONにしてset memberすると、ONにしてある利用者がグループに追加されます。</p>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<form action="{% url 'sns:groups' %}" method="post">
{% csrf_token %}
<input type="hidden" name="mode" value="__groups_form__">
{{groups_form}}
<button>select members</button>
</form>
<hr>
<form action="{% url 'sns:groups' %}" method="post">
{% csrf_token %}
<input type="hidden" name="mode" value="__friends_form__">
<input type="hidden" name="group" value="{{group}}">
{{friends_form}}
<button>set members</button>
</form>

<hr>
<p>※新しいGroupの登録</p>
<form action="{% url 'sns:creategroup' %}" method="post">
{% csrf_token %}
{{create_form}}
<button>create new group</button>
</form>
{% endblock %}

sns/templates/sns/index.html
{% extends 'sns/layout.html' %}

{% block title %}Index{% endblock %}

{% block header %}
<h1>Sns</h1>
<p class="caption">※グループのチェックをONにしてupdateすると、そのグループに登録されている利用者のメッセージだけが表示されます。</p>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<form action="{% url 'sns:index' %}" method="post">
{% csrf_token %}
<input type="hidden" name="mode" value="__search_form__">
{{search_form}}
<button>Search</button>
</form>
<hr>
<form action="{% url 'sns:index' %}" method="post">
{% csrf_token %}
<input type="hidden" name="mode" value="__check_form__">
{{check_form}}
<button>update</button>
</form>
{% for item in contents %}
<hr>
<div class="balloon">
<p class="message_public">
{% if item.group.title == 'main' %}
[main]
{% endif %}</p>
<p class="message_content">{{item.content}}</p>
<p class="message_date"> ({{item.pub_date}})</p>
{% if item.share_id > 0 %}
    <hr class="share_line">
    <p class="share_item_content">{{item.get_share}}</P>
{% endif %}
<p class="message_owner">
    <span class="message_counter">share={{item.share_count}} good={{item.good_count}}</span>
    "{{item.owner}}" (<a href="{% url 'sns:add' %}?name={{item.owner}}">add friend</a>)
    <a href="{% url 'sns:share' item.id %}"><button>share</button></a>
    <a href="{% url 'sns:good' item.id %}"><button>good!</button></a>
</p>
</div>
{% endfor %}
{% endblock %}

sns/templates/sns/layout.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" 
        href="{% static 'sns/style.css' %}" />
</head>
<body>
    <div class="body_content">
    <div class="body_content_inner">
        <table class="login_table" width="100%">
        <tr><th width="150px">menu</th><td>
        <table class="login_table_inner">
        <tr>
        <td><a href="{% url 'sns:index' %}">top</a></td>
        <td><a href="{% url 'sns:post' %}">post</a></td>
        <td><a href="{% url 'sns:groups' %}">group</a></td>
        </tr>
        </table>
        </td></tr>
        <tr><th width="150px">login user:</th><td>"{{login_user}}"</td></tr>
        </table>
        <div class="header">{% block header %}{% endblock %}</div>
        <div class="content">{% block content %}{% endblock %}</div>
        <div class="footer">
        <hr>
        <div>
        <span style="float:left;font-weight:bold;"><a href="/admin/logout?next=/sns/">[ logout ]</a></span>
        <span style="float:right">copyright 2020 </span>
        </div>
        </div>
    </div>
    </div>
</body>
</html>

sns/templates/sns/post.html
{% extends 'sns/layout.html' %}

{% block title %}Post{% endblock %}

{% block header %}
<h1>Post</h1>
<p class="caption">※投稿者のグループを選択し、メッセージを投稿します。</p>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags}}"
        {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<form action="{% url 'sns:post' %}" method="post">
{% csrf_token %}
<table>
{{form.as_table}}
<tr><td></td><td><button>Post!</button></td></tr>
</table>
</form>
{% endblock %}

sns/templates/sns/share.html
{% extends 'sns/layout.html' %}

{% block title %}Share{% endblock %}

{% block header %}
<h1>Share<h1>
<p class="caption">※投稿者のグループを選択し、下のメッセージをシェアします。</p>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags}}">
        {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<p class="share_content">{{share.content}} ({{share.pwner}})</p>
<form action="{% url 'sns:share' share.id %}" method="post">
{% csrf_token %}
<table>
{{form.as_table}}
<tr><td></td><td><button>Share!</button></td></tr>
</table>
</form>
{% endblock %}